/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.8 at Sun Jan 28 10:24:09 2018. */

#ifndef PB_VOYAGER_ESC_INTERFACE_PB_H_INCLUDED
#define PB_VOYAGER_ESC_INTERFACE_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _voyager_EscExchangeStateRequest {
    float throttle_position;
/* @@protoc_insertion_point(struct:voyager_EscExchangeStateRequest) */
} voyager_EscExchangeStateRequest;

typedef struct _voyager_EscExchangeStateResponse {
    float motor_rpm;
/* @@protoc_insertion_point(struct:voyager_EscExchangeStateResponse) */
} voyager_EscExchangeStateResponse;

typedef struct _voyager_EscRequest {
    pb_size_t which_request;
    union {
        voyager_EscExchangeStateRequest esc_exchange_state_request;
    } request;
/* @@protoc_insertion_point(struct:voyager_EscRequest) */
} voyager_EscRequest;

typedef struct _voyager_EscResponse {
    pb_size_t which_response;
    union {
        voyager_EscExchangeStateResponse esc_exchange_state_response;
    } response;
/* @@protoc_insertion_point(struct:voyager_EscResponse) */
} voyager_EscResponse;

/* Default values for struct fields */

/* Initializer values for message structs */
#define voyager_EscExchangeStateRequest_init_default {0}
#define voyager_EscExchangeStateResponse_init_default {0}
#define voyager_EscRequest_init_default          {0, {voyager_EscExchangeStateRequest_init_default}}
#define voyager_EscResponse_init_default         {0, {voyager_EscExchangeStateResponse_init_default}}
#define voyager_EscExchangeStateRequest_init_zero {0}
#define voyager_EscExchangeStateResponse_init_zero {0}
#define voyager_EscRequest_init_zero             {0, {voyager_EscExchangeStateRequest_init_zero}}
#define voyager_EscResponse_init_zero            {0, {voyager_EscExchangeStateResponse_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define voyager_EscExchangeStateRequest_throttle_position_tag 1
#define voyager_EscExchangeStateResponse_motor_rpm_tag 1
#define voyager_EscRequest_esc_exchange_state_request_tag 1
#define voyager_EscResponse_esc_exchange_state_response_tag 1

/* Struct field encoding specification for nanopb */
extern const pb_field_t voyager_EscExchangeStateRequest_fields[2];
extern const pb_field_t voyager_EscExchangeStateResponse_fields[2];
extern const pb_field_t voyager_EscRequest_fields[2];
extern const pb_field_t voyager_EscResponse_fields[2];

/* Maximum encoded size of messages (where known) */
#define voyager_EscExchangeStateRequest_size     5
#define voyager_EscExchangeStateResponse_size    5
#define voyager_EscRequest_size                  7
#define voyager_EscResponse_size                 7

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define ESC_INTERFACE_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
