/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.8 at Sun Jan 28 10:24:09 2018. */

#include "esc_interface.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t voyager_EscExchangeStateRequest_fields[2] = {
    PB_FIELD(  1, FLOAT   , SINGULAR, STATIC  , FIRST, voyager_EscExchangeStateRequest, throttle_position, throttle_position, 0),
    PB_LAST_FIELD
};

const pb_field_t voyager_EscExchangeStateResponse_fields[2] = {
    PB_FIELD(  1, FLOAT   , SINGULAR, STATIC  , FIRST, voyager_EscExchangeStateResponse, motor_rpm, motor_rpm, 0),
    PB_LAST_FIELD
};

const pb_field_t voyager_EscRequest_fields[2] = {
    PB_ONEOF_FIELD(request,   1, MESSAGE , ONEOF, STATIC  , FIRST, voyager_EscRequest, esc_exchange_state_request, esc_exchange_state_request, &voyager_EscExchangeStateRequest_fields),
    PB_LAST_FIELD
};

const pb_field_t voyager_EscResponse_fields[2] = {
    PB_ONEOF_FIELD(response,   1, MESSAGE , ONEOF, STATIC  , FIRST, voyager_EscResponse, esc_exchange_state_response, esc_exchange_state_response, &voyager_EscExchangeStateResponse_fields),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(voyager_EscRequest, request.esc_exchange_state_request) < 65536 && pb_membersize(voyager_EscResponse, response.esc_exchange_state_response) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_voyager_EscExchangeStateRequest_voyager_EscExchangeStateResponse_voyager_EscRequest_voyager_EscResponse)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(voyager_EscRequest, request.esc_exchange_state_request) < 256 && pb_membersize(voyager_EscResponse, response.esc_exchange_state_response) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_voyager_EscExchangeStateRequest_voyager_EscExchangeStateResponse_voyager_EscRequest_voyager_EscResponse)
#endif


/* @@protoc_insertion_point(eof) */
